[fix] plsplswork

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -14,57 +14,38 @@ env:
 
 jobs:
 
-  not_test_job:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout GH repository
-        uses: actions/checkout@v4
-        with:
-          repository: ' '
-      - name: No test job
-        run:  |
-          if [[ "${{github.repository}}" == "git@github.com:remythai/chocolatine.git"]]; then
-            echo "No test are run in this job. It stops immediately."
-            exit 1
-          else
-            exit 0
-          fi
+    coding-style:
+          name: Run Banana
+          runs-on: ubuntu-latest
+          container: 
+              image: ghcr.io/epitech/coding-style-checker:latest
+          
+          steps:
 
-  coding_style:
-    runs-on: ubuntu-latest
-    name: Run Banana
-    container:
-        image: ghcr.io/epitech/coding-style-checker:latest
+              - name: Checkout GH repo
+                uses: actions/checkout@master
 
-    steps:
+              - name: Run coding-style checker
+                run: check.sh $(pwd) $(pwd)
 
-      - name: Checkout GH repo
-        uses: actions/checkout@v4
+              - name: Report banana result
+                run:  |
+                  NB_ERROR=$(cat coding-style-reports.log |
+                  wc -l)
+                  if [ $NB_ERROR -gt 0 ]; then
+                    ERROR=$(cat coding-style-reports.log)
+                    echo "::error title=$NB_ERROR errors
+                    found::$ERROR"
+                    exit 1
+                  fi
+                  exit 0
 
-      - name: Run Coding-style Checker
-        run: |
-          docker run --rm -v $(pwd):/workspace ghcr.io/epitech/coding-style-checker:latest /bin/bash -c "check.sh \$(pwd) \$(pwd)"
-        continue-on-error: true
-
-      - name: Report banana result
-        run: |
-          NB_ERROR=$(cat coding-style-reports.log |
-          wc -l)
-          if [ $NB_ERROR -gt 0 ]; then
-            ERROR=$(cat coding-style-reports.log)
-            echo "::error title=$NB_ERROR errors
-            found::$ERROR"
-            exit 1
-          fi
-          exit 0
-
-  compile:
+    compile:
         runs-on: ubuntu-latest
-        needs: coding-style
         steps:
 
             - name: Checkout GH repo
-              uses: actions/checkout@v4
+              uses: actions/checkout@master
 
             - name: Compile repository
               run: make
@@ -78,25 +59,25 @@ jobs:
                 fi
                 exit 0
 
-  run-tests:
-      runs-on: ubuntu-latest
-      name: Run Unit & Integration Tests
-      container: epitechcontent/epitest-docker:latest
-      needs: compile
+    run-tests:
+        runs-on: ubuntu-latest
+        name: Run Unit & Integration Tests
+        container: epitechcontent/epitest-docker:latest
+        needs: [compile, coding-style]
 
-      steps:
+        steps:
 
-          - name: Checkout GH repo
-            uses: actions/checkout@master
+            - name: Checkout GH repo
+              uses: actions/checkout@master
 
-          - name: Compile tests binaries
-            run:  make compile_tests
+            - name: Compile tests binaries
+              run:  make compiles_tests
 
-          - name: Run unit tests
-            run: ./unit_testing
+            - name: Run unit tests
+              run: ./unit_testing
 
-          - name: Run integration tests
-            run:  ./integration_testing
+            - name: Run integration tests
+              run:  ./integration_testing
 
   push_to_mirror:
     name: Push to Mirror Repository
